### ISSUE TITLE
Error occurring when using Valibot validation.

### ISSUE THREAD

**Issue by cwoolum** [fabian-hiller/modular-forms#129]
When trying to submit a form, I receive the following error.

```
TypeError: (intermediate value)(intermediate value)(intermediate value).parse is not a function
    at valiFormQrl_b4MyjhrwMxE (C:/workspace/node_modules/@modular-forms/qwik/dist/index.qwik.mjs:870:90)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeQRL (C:/workspace/node_modules/@builder.io/qwik/core.mjs:8295:24)
    at async Object.formActionQrl_globalActionQrl_VOLgKQUpNuc (C:/workspace/node_modules/@modular-forms/qwik/dist/index.qwik.mjs:791:32)
    at async Object.invokeQRL (C:/workspace/node_modules/@builder.io/qwik/core.mjs:8295:24)
    at async measure (C:\workspace\node_modules\@builder.io\qwik-city\vite\index.cjs:24620:12)
    at async C:\workspace\node_modules\@builder.io\qwik-city\vite\index.cjs:24357:44
    at async Object.next (C:\workspace\node_modules\@builder.io\qwik-city\vite\index.cjs:24735:9)
    at async handleRedirect (C:\workspace\node_modules\@builder.io\qwik-city\vite\index.cjs:24551:7)       
    at async Object.next (C:\workspace\node_modules\@builder.io\qwik-city\vite\index.cjs:24735:9)
```

The code is related to this block

``` ts
function valiFormQrl(schema) {
  return /* @__PURE__ */ inlinedQrl(async (values) => {
    const [schema2] = useLexicalScope();
    try {
      const resolvedSchema = await schema2.resolve();
      await (typeof resolvedSchema === "function" ? resolvedSchema() : resolvedSchema).parse(values, {
        abortPipeEarly: true
      });
      return {};
    } catch (error) {
      return error.issues.reduce((errors, issue) => ({
        ...errors,
        [issue.path.map(({ key }) => key).join(".")]: issue.message
      }), {});
    }
  }, "valiFormQrl_b4MyjhrwMxE", [
    schema
  ]);
}
``` 

My schema looks like this:

``` ts
export const BarFormSchema = object({
  name: string(),
  location: object({
    address1: string(),
    address2: optional(string()),
    cityName: string(),
    stateCode: string(),
    postalCode: string(),
    x: optional(number()),
    y: optional(number()),
  }),
  images: array(special<NoSerialize<Blob>>(isBlob)),
  drinks: optional(array(string())),
  foodType: optional(string()),
  venueCapacity: optional(number()),
  channelIds: optional(array(string())),
  preferredSportsIds: optional(array(string())),
  favoriteTeamsIds: optional(array(string())),
  availableSportsIds: optional(array(string())),
  availableChannelsIds: optional(array(string())),
  hours: optional(
    array(
      object({
        day: enumType([
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
          "Sunday",
        ]),
        open: string(),
        close: string(),
      })
    )
  ),
});
```

I tried to debug into what's happening a bit. `schema2.resolve()` returns the following object.

``` ts
{
  schema: 'object',
  object: {
    name: { schema: 'string', async: false, _parse: [Function: _parse] },
    location: {
      schema: 'object',
      object: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    images: {
      schema: 'array',
      array: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    drinks: {
      schema: 'optional',
      wrapped: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    foodType: {
      schema: 'optional',
      wrapped: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    venueCapacity: {
      schema: 'optional',
      wrapped: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    channelIds: {
      schema: 'optional',
      wrapped: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    preferredSportsIds: {
      schema: 'optional',
      wrapped: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    favoriteTeamsIds: {
      schema: 'optional',
      wrapped: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    availableSportsIds: {
      schema: 'optional',
      wrapped: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    availableChannelsIds: {
      schema: 'optional',
      wrapped: [Object],
      async: false,
      _parse: [Function: _parse]
    },
    hours: {
      schema: 'optional',
      wrapped: [Object],
      async: false,
      _parse: [Function: _parse]
    }
  },
  async: false,
  _parse: [Function: _parse]
}
```

This object has a `_parse` method on it but not a `parse` method. I think this is reason the error is being thrown. I can't figure out why that method is missing though. Do you see anything I've done that is incorrect?

Versions

@modular-forms/qwik:  0.20.1
@builder.io/qwik: 1.2.7,
builder.io/qwik-city: 1.2.7,

**Comment by fabian-hiller** [comment]
Please downgrade Valibot to v0.12.0 with `pnpm i valibot@0.12.0`. I fix it for v0.13.0 with an update for Modular Forms in the next 3 hours.

**Comment by fabian-hiller** [comment]
If you upgrade to the latest Valibot and Modular Forms version, the problem should be fixed now.

**Comment by jirihybek** [comment]
Hi, I ran into the same issue. I've upgraded both Module Forms and Valibot to the latest version and am still getting the error:

```
TypeError: (intermediate value)(intermediate value)(intermediate value).parse is not a function
```

valibot: 0.13.1
@modular-forms/qwik: 0.20.2

**Comment by fabian-hiller** [comment]
@jirihybek please check again, if your package manager have installed the right versions into `/node_modules`. If there is still a problem, please share more details with me.
