### ISSUE TITLE
Are there any examples of using forms in different components?

### ISSUE THREAD

**Issue by jmcelreavey** [fabian-hiller/modular-forms#56]
I was wondering if there's any example of passing a Qwik action and loader into another component file. Currently I get linting errors for using them outside of the root.

I know I'm likely doing something silly so I'm wondering if there're any examples?

I'd also like to return the on submit event to the parent component on submit.

**Comment by fabian-hiller** [comment]
Can you provide me with some code examples? I plan to extend the documentation in this area. Currently we only have this: https://modularforms.dev/qwik/guides/typescript

**Comment by jmcelreavey** [comment]
Awesome that's really useful. How would I propagate the submit values to the parent components?

```
import { component$ } from "@builder.io/qwik";
import { z } from "@builder.io/qwik-city";
import type { FormStore } from "@modular-forms/qwik";
import { Field, Form } from "@modular-forms/qwik";
import { Button } from "../base/Button";
import { DivError } from "../base/DivError";
import { Input } from "../base/Input";
import { Label } from "../base/Label";

export const searchSchema = z.object({
    searchPhrase: z.string(),
});

export type SearchForm = z.input<typeof searchSchema>;

export const Search = component$(
    ({ searchForm }: { searchForm: FormStore<SearchForm, SearchForm> }) => {
        return (
            <Form of={searchForm} class="mb-8">
                <Field type="string" of={searchForm} name="searchPhrase">
                    {(field, props) => (
                        <>
                            <Label for={field.name}>
                                Search Restaurants, Location and Postcodes:
                            </Label>
                            <Input isError={Boolean(field.error)} {...props} value={field.value} />
                            <Button>Search</Button>
                            <DivError>{field.error}</DivError>
                        </>
                    )}
                </Field>
            </Form>
        );
    }
);
```

I have a small search component

**Comment by fabian-hiller** [comment]
To do this, you must define a function in the parent component that takes the values and adds them to a signal, for example. You can then pass this function to children via `props` and then call it there to pass data up the tree. Or have I misunderstood you?

**Comment by jmcelreavey** [comment]
Yeah I was thinking that was my best option but I just wanted to check in case there was some way of getting access to the values on the `useSearchFormLoader()` in the parent or an `action` being passed into the `useFormStore`

**Comment by jmcelreavey** [comment]
Any idea why this action isn't getting fired?

```
import { component$, Resource, useResource$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { server$ } from "@builder.io/qwik-city";
import { routeLoader$ } from "@builder.io/qwik-city";
import type { InitialValues } from "@modular-forms/qwik";
import { formAction$, zodForm$ } from "@modular-forms/qwik";
import { useFormStore } from "@modular-forms/qwik";
import type { Member } from "@prisma/client";
import { DivGrid } from "~/components/base/DivGrid";
import { H1 } from "~/components/base/H1";
import { Main } from "~/components/base/Main";
import { P } from "~/components/base/P";
import type { SearchForm } from "~/components/restaurants/Search";
import { searchSchema } from "~/components/restaurants/Search";
import { Search } from "~/components/restaurants/Search";
import { prisma } from "~/db";

export const useSearchFormLoader = routeLoader$<InitialValues<SearchForm>>(() => ({
    searchPhrase: "",
}));

export const useSearchFormAction = formAction$<SearchForm, Member[]>(async ({ searchPhrase }) => {
    const members = await prisma.member.findMany({
        where: {
            OR: [
                {
                    email: {
                        contains: searchPhrase,
                    },
                },
            ],
        },
    });

    return {
        status: "success",
        message: "Members found:",
        data: members,
    };
}, zodForm$(searchSchema));

export default component$(() => {
    const loader = useSearchFormLoader();
    const action = useSearchFormAction();
    const searchForm = useFormStore<SearchForm, Member[]>({ loader, action });
    const restaurantResource = useResource$<Member[]>(async (ctx) => {
        ctx.track(() => searchForm.response.data);
        return server$(async () => {
            return searchForm.response?.data || (await prisma.member.findMany({}));
        })();
    });

    return (
        <Main>
            <H1>Discover Northern Ireland's Best Restaurants</H1>
            <P>
                Find the perfect spot for your next meal in Belfast, Derry, or anywhere in between
                with our directory of top-rated restaurants in Northern Ireland. Simply enter your
                address or location to browse our listings and discover everything from cozy local
                favorites to fine dining experiences. Our comprehensive directory makes it easy to
                treat your taste buds to a culinary adventure, with something for every taste and
                budget. Start exploring today!
            </P>
            <Search searchForm={searchForm} />
            <DivGrid>
                <Resource
                    value={restaurantResource}
                    onPending={() => <div>Loading restaurants...</div>}
                    onResolved={(restaurants) => (
                        <>
                            {restaurants &&
                                restaurants.map((restaurant, id) => (
                                    <div key={id}>{restaurant.email}</div>
                                ))}
                        </>
                    )}
                />
            </DivGrid>
        </Main>
    );
});

export const head: DocumentHead = {
    title: "Taste of NI | Northern Ireland Restaurants Directory",
    meta: [
        {
            name: "description",
            content: "a restaurant directory for Northern Ireland",
        },
    ],
};
```

**Comment by jmcelreavey** [comment]
Here's the search component:

```
import { component$ } from "@builder.io/qwik";
import { z } from "@builder.io/qwik-city";
import type { FormStore } from "@modular-forms/qwik";
import { Field, Form } from "@modular-forms/qwik";
import { Button } from "../base/Button";
import { DivError } from "../base/DivError";
import { Input } from "../base/Input";
import { Label } from "../base/Label";
import type { Member } from "@prisma/client";

export const searchSchema = z.object({
    searchPhrase: z.string(),
});

export type SearchForm = z.input<typeof searchSchema>;

export const Search = component$(
    ({ searchForm }: { searchForm: FormStore<SearchForm, Member[]> }) => {
        return (
            <Form of={searchForm} class="mb-8">
                <Field type="string" of={searchForm} name="searchPhrase">
                    {(field, props) => (
                        <>
                            <Label for={field.name}>
                                Search Restaurants, Location and Postcodes:
                            </Label>
                            <Input isError={Boolean(field.error)} {...props} value={field.value} />
                            <Button type="submit">Search</Button>
                            <DivError>{field.error}</DivError>
                        </>
                    )}
                </Field>
            </Form>
        );
    }
);
```

**Comment by fabian-hiller** [comment]
Yes, you forgot to pass `action` to the `Form` component. `useForm` does this automatically. For `useFormStore` you have to do it yourself. Sorry, I just saw that I forgot to specify `action` in the API reference. I'll fix that.

**Comment by jmcelreavey** [comment]
Actually I can't seem to get server calls to work at all in the latest Qwik, Getting an error from Qwik about finding the objectId here's my current code:

```
import type { QRL } from "@builder.io/qwik";
import { $, component$, Resource, useResource$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { routeLoader$, server$ } from "@builder.io/qwik-city";
import type { InitialValues, SubmitHandler } from "@modular-forms/qwik";
import { formAction$, useForm, zodForm$ } from "@modular-forms/qwik";
import type { Member } from "@prisma/client";
import { Button } from "~/components/base/Button";
import { DivError } from "~/components/base/DivError";
import { DivGrid } from "~/components/base/DivGrid";
import { H1 } from "~/components/base/H1";
import { Input } from "~/components/base/Input";
import { Label } from "~/components/base/Label";
import { Main } from "~/components/base/Main";
import { P } from "~/components/base/P";
import type { SearchForm } from "~/components/restaurants/Search";
import { searchSchema } from "~/components/restaurants/Search";
import { prisma } from "~/db";

export const useSearchFormLoader = routeLoader$<InitialValues<SearchForm>>(() => ({
    searchPhrase: "",
}));

export const useSearchFormAction = formAction$<SearchForm>((values) => {
    // Runs on server
    console.log(values);
}, zodForm$(searchSchema));

export default component$(() => {
    const loader = useSearchFormLoader();
    const action = useSearchFormAction();
    const [searchForm, { Form, Field }] = useForm<SearchForm>({ loader, action });
    const restaurantResource = useResource$<Member[]>(async (ctx) => {
        ctx.track(() => searchForm.response.data);
        return server$(async () => {
            return searchForm.response?.data || (await prisma.member.findMany({}));
        })();
    });

    const handleSubmit: QRL<SubmitHandler<SearchForm>> = $((values, event) => {
        // Runs on client
        alert("here");
    });

    return (
        <Main>
            <H1>Discover Northern Ireland's Best Restaurants</H1>
            <P>
                Find the perfect spot for your next meal in Belfast, Derry, or anywhere in between
                with our directory of top-rated restaurants in Northern Ireland. Simply enter your
                address or location to browse our listings and discover everything from cozy local
                favorites to fine dining experiences. Our comprehensive directory makes it easy to
                treat your taste buds to a culinary adventure, with something for every taste and
                budget. Start exploring today!
            </P>
            <Form class="mb-8" onSubmit$={handleSubmit}>
                <Field name="searchPhrase">
                    {(field, props) => (
                        <>
                            <Label for={field.name}>
                                Search Restaurants, Location and Postcodes:
                            </Label>
                            <Input isError={Boolean(field.error)} {...props} value={field.value} />
                            <DivError>{field.error}</DivError>
                        </>
                    )}
                </Field>
                <Button type="submit">Search</Button>
            </Form>
            <DivGrid>
                <Resource
                    value={restaurantResource}
                    onPending={() => <div>Loading restaurants...</div>}
                    onResolved={(restaurants) => (
                        <>
                            {restaurants &&
                                restaurants.map((restaurant, id) => (
                                    <div key={id}>{restaurant.email}</div>
                                ))}
                        </>
                    )}
                />
            </DivGrid>
        </Main>
    );
});

export const head: DocumentHead = {
    title: "Taste of NI | Northern Ireland Restaurants Directory",
    meta: [
        {
            name: "description",
            content: "a restaurant directory for Northern Ireland",
        },
    ],
};
```

**Comment by fabian-hiller** [comment]
I can't find a bug in your code in the first view. If it doesn't cause you any problems on the other side, I would downgrade to an older Qwik version in which it still worked. Optionally you can also create an issue at Qwik with the problem. Then it will probably be fixed until the next version.

**Comment by jmcelreavey** [comment]
Ah it seems for some reason I can't do
`ctx.track(() => searchForm.response.data);`

**Comment by fabian-hiller** [comment]
The `response` is always set as a whole. So it probably only works if you return the `response` object.

**Comment by jmcelreavey** [comment]
Strange that doesn't work either. it doesn't seem to be able to watch it either. If I console.log() what it tracks for `searchForm.response` I get:
`{ Symbol(proxy flags): 1 }` so my guess is it's trying to watch the form too early and not able to get a handle on it?

**Comment by fabian-hiller** [comment]
I was able to track the response in the [`Response`](https://github.com/fabian-hiller/modular-forms/blob/main/playgrounds/qwik/src/components/Response.tsx) component of our playground. But I remember that I also had problems when I implemented it.

**Comment by jmcelreavey** [comment]
You don't happen to still have a record of that playground for me to have a nosy?

**Comment by fabian-hiller** [comment]
https://stackblitz.com/edit/modular-forms-qwik-actions?file=src%2Fcomponents%2FResponse.tsx

**Comment by fabian-hiller** [comment]
Were you able to solve the problem?

**Comment by jmcelreavey** [comment]
Yeah it seemed to be something strange with the <Resource /> in Qwik being rendered too late. When I removed that it worked fine. 🤷‍♂️ Thanks for your link though, that was really useful.
