### ISSUE TITLE
[bug] formAction$ behaves differently on redirect than globalAction$

### ISSUE THREAD

**Issue by tuurbo** [fabian-hiller/modular-forms#59]
When you submit with a formAction$, the routeLoader$ fires and then fires again after the redirect.  But, if you redirect from within qwik's globalAction$ instead, routeLoader correctly only fires once (after the redirect).

I think the problem is formAction$ shouldn't fire all loaders again before the redirect.

steps to reproduce:
https://github.com/tuurbo/qwik-form-actions

## qwik form (correct behavior)
- click login link
- click "login (qwik)" button
- should see below in server console
```
loader /
loader /login/
formLoader
action (qwik)
loader /q-data.json
```

## modular form (bad behavior)
- clear server console
- click login link
- click "login (modular)" button
- should see below in server console
```
loader /
loader /login/
formLoader
action (modular)
RedirectMessage {}             <----- not sure why this is logged
loader /login/q-data.json      <----- this should not be called
formLoader                     <----- this should not be called
loader /q-data.json
```

**Comment by fabian-hiller** [comment]
Thank you very much for your attention. Do you have any idea what I can do differently? `formAction$` builds on `globalAction$` and adds nothing in this regard. Here is the code: https://github.com/fabian-hiller/modular-forms/blob/main/packages/qwik/src/actions/formAction%24.ts

**Comment by tuurbo** [comment]
I found the culprit, but I'm not exactly sure how to fix it.
When you redirect in qwik, you prepend the `event.redirect()` with `throw`. (eg: `throw event.redirect(302, '/')`).

The throw is being caught by this try/catch statement. Which explains why `RedirectMessage {}` is logged to the console.
https://github.com/fabian-hiller/modular-forms/blob/main/packages/qwik/src/actions/formAction%24.ts#L117

Maybe in the catch we could rethrow the error, eg:
```js
if (error instanceof AbortMessage) {
  throw error;
}
```

Here are the AbortMessage and RedirectMessage Qwik classes. They don't seem to be public though.
https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/middleware/request-handler/redirect-handler.ts

Maybe you know another way to go about it?

**Comment by fabian-hiller** [comment]
Thanks a lot for your research! I will look into it and fix it in the next few days.

**Comment by fabian-hiller** [comment]
As soon as I get feedback from Qwik on my issue, I will work out a solution to this problem.

**Comment by fabian-hiller** [comment]
I created a PR to speed up the process: https://github.com/BuilderIO/qwik/pull/4077

**Comment by fabian-hiller** [comment]
My PR has been merged. As soon as the new Qwik version is available, I will add the if statement.

**Comment by fabian-hiller** [comment]
The new version is available. 🎉

**Comment by tuurbo** [comment]
Thanks! 

Note: It doesn't work in dev but does work in prod. If I manually edit the modular form code in node_modules and insert `console.log(error instanceof AbortMessage);` it returns `false` but in prod it returns `true`. Not sure anything can be done about that but I wanted to note it in case someone else runs into this issue.

**Comment by fabian-hiller** [comment]
I have the problem in dev too. However, I assume that this is not a technical problem with the code, but with the package manager. I assume that the `AbortMessage` class exists multiple times and is not obtained from the same source in each case. Because of this `instanceof AbortMessage` does not work.

**Comment by juanpmarin** [comment]
@fabian-hiller is there a way to make this work on dev? I'm not being able to do redirections

**Comment by juanpmarin** [comment]
It is failling with latest version of qwik, [v1.2.5](https://github.com/BuilderIO/qwik/releases/tag/v1.2.5)
Both in dev and prod

**Comment by fabian-hiller** [comment]
Thank you for the hint. I will investigate this.

**Comment by fabian-hiller** [comment]
@juanpmarin in Qwik v.1.1.5 both works for me. Dev and preview. In Qwik v1.2.5 only dev works. With preview I get an error in the console. If I upgrade Modular Forms Qwik to v1.2.5 it behaves the same, except that I get a different error in the console. I recommend downgrading your Qwik version until we find a solution for the problem. I suspect it is a Qwik issue and not a Modular Forms issue. Feel free to create an issue in the Qwik repo with the errors you are getting and link this issue.

**Comment by juanpmarin** [comment]
@fabian-hiller do you know about a workaround for this?

**Comment by fabian-hiller** [comment]
Downgrade to Qwik v1.1.5

**Comment by fabian-hiller** [comment]
I have the problem. That's why I created [this issue](https://github.com/BuilderIO/qwik/issues/4789). Until this is fixed, I recommend downgrading to v1.1.5.

**Comment by fabian-hiller** [comment]
It occurs when you use the `formAction$` API of Modular Forms. However, I strongly believe that Qwik is the problem and that we as a library cannot do anything.

**Comment by fabian-hiller** [comment]
Problem with Qwik 1.2.X should be fixed in v0.20.0 of Modular Forms. Make sure, this two imports are imported in the following order in `entry.preview.tsx`:

```ts
import qwikCityPlan from "@qwik-city-plan"; 
import render from "./entry.ssr";
```

**Comment by juanpmarin** [comment]
@fabian-hiller are you sure that fix is for this issue? I've upgraded qwik and modular forms and redirection still does not work

**Comment by fabian-hiller** [comment]
@juanpmarin my comment was related to the previous comments on the Qwik 1.2.6 problem. I will fix the problem you describe soon. In production it should work normally.

**Comment by juanpmarin** [comment]
Hi @fabian-hiller !
I would love to upgrade qwik to the latest version, do you have any clues about why redirection is not working? Maybe I can do some research

**Comment by fabian-hiller** [comment]
Does it not work in production either? This could be a possible fix for dev: https://github.com/fabian-hiller/modular-forms/pull/66

**Comment by juanpmarin** [comment]
@fabian-hiller that fix makes sense to me, it could even stay enabled in production, what do you think?

**Comment by fabian-hiller** [comment]
I would only activate it in dev. In prod it has no use. I will release a new version with the change in the next weeks. If you want to speed up the process, you can revise the PR or create a new one.

**Comment by juanpmarin** [comment]
@fabian-hiller redirects are not working for me in production either, I suspect of `qwik-speak`, because it duplicates de bundle for every language, does that make sense to you?

**Comment by fabian-hiller** [comment]
Does it work for your without `qwik-speak`? Which Qwik version are you using?

**Comment by juanpmarin** [comment]
Hi @fabian-hiller I did some more tests, I tried to upgrade my project to the latest Qwik and modular forms version again, redirect still does not work but for a different reason I think, look:

I found that when I submit the form, a 404 status code is received:
![image](https://github.com/fabian-hiller/modular-forms/assets/13415603/4c32319a-ba75-4048-85e2-ee48b1b75528)

I tried to look for that action id in the server bundle and I found a similar one, only the prefix changes from `id_` to `s_`
If I fix the id in the URL, and try to execute the same request with curl, I get a success response

Original path: `/quotes/new/q-data.json?qaction=id_AW14dmUcJXw`
Modified path: `/quotes/new/q-data.json?qaction=s_AW14dmUcJXw`

Do you have any idea of why is not the right id being sent?

**Comment by fabian-hiller** [comment]
If you don't need any of the new features, I recommend downgrading Qwik. Currently I have very little time, so I don't know when I can look at the problem. Probably it is a problem on the Qwik's side. Feel free to create an issue there and link me.

**Comment by fabian-hiller** [comment]
I understand. As long as the problem can be solved by changes to Modular Forms, I am very interested in implementing those changes directly. Since `formAction$` is not extremely complicated and basically just builds on `globalAction$`, it should be quick once I know what to do.
